stages:
  - lint
  - check-models
  - test

image: altwalker/altwalker:latest

python-ecommerce-lint:
  stage: lint
  before_script:
    - cd python-ecommerce
    - pip3 install flake8
  script:
    - flake8 --max-line-length=120 tests

python-ecommerce-check-models:
  stage: check-models
  before_script:
    - cd python-ecommerce
  script:
    - altwalker check -m models/navigation.json "random(never)" -m models/checkout.json "random(never)"

python-ecommerce-tests:
  stage: test
  before_script:
    - source install_firefox.sh
    - cd python-ecommerce
    - pip3 install -r requirements.txt --user
  script:
    - altwalker verify -m models/navigation.json tests
    - altwalker online -m models/navigation.json "random(length(40))" tests
    - altwalker online -m models/navigation.json "random(length(20))" -m models/checkout.json "random(vertex_coverage(100))" tests
  artifacts:
    paths:
      - "*.log"
    when: always

dotnet-ecommerce-check-models:
  stage: check-models
  before_script:
    - cd dotnet-ecommerce
  script:
    - altwalker check -m models/navigation.json "random(never)" -m models/checkout.json "random(never)"

dotnet-ecommerce-tests:
  stage: test
  image: altwalker/tests:dotnet-v2.2
  before_script:
    - source install_firefox.sh
    - pip3 install idna==2.8
    - pip3 install altwalker
    - cd dotnet-ecommerce
  script:
    - dotnet build tests
    - altwalker verify -l c# -m models/navigation.json -m models/checkout.json tests
    - altwalker online -l c# -m models/navigation.json "random(length(40))" tests
    - altwalker online -l c# -m models/navigation.json "random(length(20))" -m models/checkout.json "random(vertex_coverage(100))" tests
  artifacts:
    paths:
      - "*.log"
    when: always
