name: Python Auth

on:
  push:
    paths:
      - 'python-auth/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup AltWalker
      uses: altwalker/setup-altwalker@main

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --max-line-length 120 python-auth

    - name: Install pip dependencies
      run: |
        cd python-auth
        pip install -r requirements.txt

    - name: Check the models
      run: |
        cd python-auth
        altwalker check -m models/models.json "random(never)"

    - name: Start server
      run: |
        pip install django==3.0.3
        pip install django-crispy-forms
        git clone https://github.com/altwalker/django-auth.git
        cd django-auth
        python manage.py migrate
        python manage.py runserver &

    - name: Verify the code
      run: |
        cd python-auth
        altwalker verify -m models/models.json tests

    - name: Run the tests
      run: |
        cd python-auth
        altwalker online -m models/models.json "random(edge_coverage(100))" tests

    - name: Archive log files
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: logs
        path: '**/*.log'
