name: Python Config

on:
  push:
    paths:
      - 'python-config/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup AltWalker
      uses: altwalker/setup-altwalker@main

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --max-line-length 120 python-config

    - name: Install pip dependencies
      run: |
        cd python-config
        pip install -r requirements.txt

    - name: Check the models
      run: |
        cd python-config
        altwalker check -m models/model.json "random(never)"

    - name: Verify the code
      run: |
        cd python-config
        altwalker verify -m models/model.json tests

    - name: Run the tests
      run: |
        cd python-config
        altwalker online -m models/model.json "random(vertex_coverage(100))" tests

    - name: Archive log files
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: logs
        path: '**/*.log'
